[versions]
mvivm = "0.1.21"
foundation = "1.4.30"

[libraries]
expect-core = { module = "tz.co.asoft:expect-core", version.ref = "foundation" }
expect-coroutines = { module = "tz.co.asoft:expect-coroutines", version.ref = "foundation" }
kotlinx-collections-atomic = { module = "tz.co.asoft:kotlinx-collections-atomic", version.ref = "foundation" }
kotlinx-coroutines-test = { module = "tz.co.asoft:kotlinx-coroutines-test", version.ref = "foundation" }
logging-console = { module = "tz.co.asoft:logging-console", version.ref = "foundation" }

[plugins]
applikation = { id = "tz.co.asoft.applikation", version.ref = "foundation" }
library = { id = "tz.co.asoft.library", version.ref = "foundation" }
deploy = { id = "tz.co.asoft.deploy", version.ref = "foundation" }